### ISSUE TITLE
Unit tests in 06-04

### ISSUE THREAD

**Issue by EliasGaliounas** [alan-turing-institute/rse-course#182]
There is a section 'Write some unit tests' which calls function 'greeter' inside function test_greeter().
At this time, the contents of function 'greeter' are from 06_03, and are simply:
def greet(personal, family):
    return "Hey, " + personal + " " + family

This does not add colour to the text, so the unit tests fail.
The definition of 'greeter' which would pass the tests appears earlier in 06_03 (but that's not the most recent definition at the time of unit testing).

**Comment by jemrobinson** [comment]
The unit test is not running the version of this file defined in the notebook. The definition comes from this line:

```python
from greetings.greeter import greet
```

which imports the function from [this file](https://github.com/alan-turing-institute/rse-course/blob/main/module06_software_projects/Greetings/greetings/greeter.py).

This definition has the coloured-text needed to make the tests pass. If you run the notebook `module06_software_projects/06_04_packaging.ipynb` in isolation you should see that all the cells run as expected.
