### ISSUE TITLE
Problems installing Anaconda on MacOS Monterey (MacOS version 12.6.2) on M1 Mac

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#184]
The GUI and command line installers fail when trying to install Anaconda on an M1 Mac running Monterey (MacOS version 12.6.2). This has been reported in [the Anaconda forum here](https://github.com/ContinuumIO/anaconda-issues/issues/12978). It seems to be a problem with Anaconda's being set up to use bash rather than zsh, although there may be some permission problems too.

I managed to get it working as follows:

1. Download the command line installer (for M1 or x86 as required).
2. Follow [the instructions here](https://docs.anaconda.com/anaconda/install/mac-os/#using-the-command-line-install), but use `sudo` to run the bash script at step 3. I.e. `sudo bash '~/Downloads/Anaconda3-2022.10-MacOSX-arm64.sh'` (replacing `~/Downloads` with the location of the installation file, and the filename with whatever version you're using. Note that you can simply type `sudo bash ` and then drag the installation file from Finder into the Terminal window to complete the command, then hit enter.
3. Enter your system/admin password when prompted.
4. After install has completed, open a bash shell (assuming you're in the default zshell), by typing `bash`.
5. Open your `~/.bash_profile` and copy the `export PATH="~/anaconda3/bin:$PATH"` command, where `~` will be whatever your install location is (user's home directory by default). Paste it into the command line and hit enter. This will add the conda location to your path. (This should happen when you open a new bash shell, due to the configuration in `.bash_profile`, but it didn't for me.)
6. Run `sudo conda init zsh`. You'll likely have to enter password again.
7. Exit from both bash and zsh sessions.
8. Re-open your terminal. Will be in zsh by default.
9. Run `conda list` to verify it's working. You'll also see that `conda init` has added a bunch of stuff to your `~/.zshrc` file.

**Comment by oC-n** [comment]
I just discovered [here](https://stackoverflow.com/a/66700298) that installing Anaconda using `sudo` is what causes the ownership problem I raised in #186 . So I uninstalled Anaconda and tried reinstalling from the command line and this time it worked without `sudo`. The only thing to note is that any Mac users running MacOS later than Catalina should follow the Catalina instructions.

**Comment by arsolust** [comment]
theres no way this shit is actually this difficult these people don't make it easy for beginners at all
