### ISSUE TITLE
Extra bracket in hashbang URL in 1.0 Introduction to Python

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#187]
In [this section](https://alan-turing-institute.github.io/rse-course/html/module01_introduction_to_python/01_00_introduction_to_python.html#python-scripts), a link is provided to Wikipedia article on the *shebang*. The link has an extra bracket at the end, which misdirects. The link instead should be `https://en.wikipedia.org/wiki/Shebang_(Unix)`.

**Comment by oC-n** [comment]
This is due to there being brackets in the URL, only one of which is escaped in the notebook. The markdown should be:
`[hashbang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29)`

**Comment by jemrobinson** [comment]
Thanks for flagging this @oC-n !
