### ISSUE TITLE
Outdated link to Software Carpentry data analysis example (1.0.1)

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#188]
In the section, [Why write software to manage your data and plots?](https://alan-turing-institute.github.io/rse-course/html/module01_introduction_to_python/01_00_introduction_to_python.html#why-write-software-to-manage-your-data-and-plots), a Software Carpentry link is given, but the target page has changed.

Old: `https://swcarpentry.github.io/python-novice-inflammation/01-numpy/index.html`
New: `https://swcarpentry.github.io/python-novice-inflammation/01-intro/index.html`

**Comment by jemrobinson** [comment]
Thanks for flagging this @oC-n !
