### ISSUE TITLE
1.2 link regarding operator precedence is no longer accessible

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#190]
The link at the end of notebook 1.2, `http://www.mathcs.emory.edu/~valerie/courses/fall10/155/resources/op_precedence.html`, refers to a page whose access is now restricted, resulting in a "403 Forbidden" response.

**Comment by oC-n** [comment]
This link to Python docs would be more appropriate & will remain accessible:
`https://docs.python.org/3/reference/expressions.html#operator-precedence`

**Comment by jemrobinson** [comment]
Thanks for flagging this @oC-n !
