### ISSUE TITLE
Inconsistencies in 2.7 Classroom Exercises & Module 2 Solutions

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#193]
1. The problem heading numbers in Module 2 solutions & the order of the solutions don't match the notebook's (2.7 Classroom Exercises).
2. Exercise 2d gives links to documentation for each library, but the docs for statistics make no mention of a log function. I found this only when the solution mentioned using `dir(library)`, and had to guess at how to use it. Eventually, looking at the source code, `statistics.py`, showed that the module simply imports the function from the `math` module.
3. The positive logarithm results shown are for base e, not base 10 as specified in the question.
4. It took a long time to find how to do log10 in scipy, using `scipy.special.xlogy` and converting to base 10. Was there previously a more direct way?
5. Using `scipy.special.xlogy` gives 'not a number' when applied to a negative number (`y < 0`), rather than a complex number as shown in the solution. The answer listed in the table does approximate `-11.99` when used as the exponent for `e`, but the only way to get that answer is if one knows to use a complex input to the `xlogy` function.

It would therefore be useful if the solutions showed how to execute the commands for 2d, if only to check they all work.

**Comment by jemrobinson** [comment]
Thanks for flagging this @oC-n !

> It took a long time to find how to do log10 in scipy, using scipy.special.xlogy and converting to base 10. Was there previously a more direct way?

`scipy` has a `scipy.log10` function. I've updated the solutions to make this clear.

**Comment by oC-n** [comment]
Hi @jemrobinson . Thanks for clarifying and updating. On testing `scipy.log10`, I found it works but gives a deprecation warning:
> DeprecationWarning: scipy.log10 is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log10 instead.
