### ISSUE TITLE
Dead link in 4.0.1

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#197]
Under the **Markdown** heading, there is a link to a file that doesn't currently exist, showing the notebook in HTML form: `[web](https://github.com/alan-turing-institute/rse-course/blob/main/module04_version_control_with_git/04_00_introduction.html)`

**Comment by jemrobinson** [comment]
Do you want to make a PR to fix this @oC-n ? Should be a nice quick one :)

**Comment by oC-n** [comment]
Can do, @jemrobinson . Was just waiting until I'm sure I've got the procedure right. I'll link to https://github.com/alan-turing-institute/rse-course/blob/gh-pages/html/module04_version_control_with_git/04_00_introduction.html

**Comment by jemrobinson** [comment]
It might be better to link to `https://alan-turing-institute.github.io/rse-course/html/module04_version_control_with_git/04_00_introduction.html` which show the processed HTML.

**Comment by oC-n** [comment]
Pull request created: https://github.com/alan-turing-institute/rse-course/pull/199
