### ISSUE TITLE
In 4.2, should `git checkout` update file from repo, not staging area?

### ISSUE THREAD

**Issue by oC-n** [alan-turing-institute/rse-course#198]
In the last diagram in the notebook, my understanding (and from my tests) suggests that "Update file to reverted version" should be a line from repo to Jim, ie `R->J: Update file to reverted version`, rather than `I->J`.

**Comment by jemrobinson** [comment]
I'm not sure about this. @Iain-S @mhauru do you know what operations `git revert` actually performs? See the last WSD on [this page](https://alan-turing-institute.github.io/rse-course/html/module04_version_control_with_git/04_02_fixing_mistakes.html) for more details.

**Comment by oC-n** [comment]
@jemrobinson , actually, the process I'm referring to is `git checkout test.md`.

**Comment by Iain-S** [comment]
Yes, I believe @oC-n is right.

As I understand it,

1. the `reset` will be `--mixed` by default so...
2. ...the "Add another mistake" `commit` will be undone (HEAD will point to the previous commit) and...
3. ...whatever changes were made in that commit (i.e. the `vim` ones) will be left in the workind directory but will be unstaged

The `checkout` will take `test.md` back to the state it was in before the `vim` changes so the whole thing is functionally equivalent to a `git reset --hard`.

**Comment by jemrobinson** [comment]
If you have time @Iain-S, can you make a PR to fix this?
