### ISSUE TITLE
Potential changes to RSE course structure

### ISSUE THREAD

**Issue by lukehare** [alan-turing-institute/rse-course#61]
Potential changes to the RSE course structure discussed during planning meeting on 19/01:

- Move Greengraph example in module 1 to end of module (rather than beginning)
- Swap order of Greengraph & Boids example in module 3
- Possibly replace Boids example in module 3 with something more useful -e.g., intro to pandas/scipy

**Comment by jemrobinson** [comment]
- In `03_00_fields_and_records` use `pandas` to load data rather than `numpy` (no real need to even introduce `numpy` at this point)
- In `03_01_structured_data` show how to read JSON and write to YAML (or vice versa). Add an XML example

**Comment by pafoster** [comment]
In `02_01_functions`, several people in the audience asked questions related to the 'Side effects' section. Because the reasons behind why we can have functions with side-effects are somewhat counter-intuitive, it might be useful to add a preceding section on scoping and to contrast the differences in behaviour using more examples (in addition to the example which involves **[:]**,  there is the possibility of demonstrating side effects by appending to a list. It might also be useful to link back to the Memory and Containers section in `01_05_containers` here.

**Comment by jemrobinson** [comment]
##  Module 4: Version control

- Reference `https://explainshell.com/` for looking up what commands are doing

**Comment by jack89roberts** [comment]
## Module 6: Software Projects

- Add something on virtual environments
- Alternatives to setup.py (e.g. for specifying dependencies, but also Python is moving towards pyproject.toml / setup.cfg )
- [NB] I’m not sure it’s really helpful to have all the stuff about the python path - I think it’s easier to just package stuff up and install it, and if we’re encouraging people to have different environments for different projects, I don’t really see a downside to that…
- Mention JOSS/similar (in the context of licensing)

Other questions that came up:
- Benefits of pip vs conda vs Poetry etc.
- How to define and maintain dependencies, check for security issues/bloat
- Need/convention for `if __name__ == "__main__"`
- Where to host docs?

(Copied a few things from the HackMD here @nbarlowATI  @edaub )

**Comment by jack89roberts** [comment]
## Module 7: Construction and Design

- We ran out of time to do the exercise properly (or at all really).
- I think there's a lot of good reference material in the module (e.g. ideas for refactorings, different OOP concepts) but not sure how well it translates into teaching. Felt a bit like reading a long list, I suspect I would have got lost if attending as a participant with limited Python/programming knowledge (but will be interesting to see feedback/hear others' thoughts).
- Questions  included:
   - Translating research/user requirements into software - could be a topic to add somewhere in the course. I ended up linking to Module 1 of the RDS course which has some discussion on scoping etc. for data science projects. 
   - How to verify refactoring doesn't change results (testing)?
   - Recommendations for/possible caveats with using linters
   - Inheriting from multiple classes
   - General questions about understanding what functions did, understanding scope etc.

**Comment by jemrobinson** [comment]
## General (all modules)
- make student exercises smaller (5 mins max each) and ensure that each 45 min session has one
- have a single larger exercise at the end of each module for students to do in their own time (after the end of the module)

**Comment by nbarlowATI** [comment]
## Module 10: Scientific file formats

There were some good questions and good discussion about other binary file formats (parquet, arrow, feather) - this could be a good thing for us to cover.

The last two notebooks on Ontologies, and Semantic Web, are difficult for a non-expert to teach - the Turtle syntax is very hard to read, and there isn't a huge amount of explanatory text.   I [NB] would be in favour of downsizing these sections considerably, and devoting the time to something else - possibly other file formats as mentioned above, or perhaps something about streaming or distributed data.

We also had a question about Docker - this could be a good thing to mention at some point in the course (not necessarily this module).

**Comment by jack89roberts** [comment]
> * Possibly replace Boids example in module 3 with something more useful -e.g., intro to pandas/scipy

Just a note that Boids is referred back to/used again several times in the course (e.g. as an exercise in Module 7), so we'd also need to find replacements there if we remove it. But the implementation in module 3 definitely could be simplified at least (the use of broadcasting is clever but gets a bit over the top IMO).

**Comment by jemrobinson** [comment]
Closing this issue as separate issues have been created for each module.
