### ISSUE TITLE
Synchronising with the UCL version of the course

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/rse-course#7]
Hi @iamleeg. When you were at the Turing last week, you mentioned that you'd been involved in updating the UCL version of this course. Do you think there's anything there that's worth combining into this course? It would be nice if we could get to a point where people simply forked one repo for their own purposes, rather than having several versions floating around.

**Comment by iamleeg** [comment]
I forked the UCL version, to make [our version](https://github.com/OxfordRSE/rsd-engineeringcourse). There's definitely room to share/combine/disagree, and I think we should probably have all three groups involved.

**Comment by jemrobinson** [comment]
With the recent changes to the structure of this repo I don't think we'll standardise on a single copy but it is still worth discussing changes between all interested groups.
